### ISSUE TITLE
OVE documentation

### ISSUE THREAD

**Issue by dsigdosystem** [ove/ove-docs#1]
<a href="https://github.com/davidbirchwork"><img src="https://avatars3.githubusercontent.com/u/11289564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [davidbirchwork](https://github.com/davidbirchwork)**
_Friday Sep 07, 2018 at 13:39 GMT_
_Originally opened as https://github.com/dsi-icl/ove/issues/7_

----

Suggest using http://apidocjs.com/#getting-started to self document the API's for the apps and core 

(a note for ove v0.2)

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Friday Sep 14, 2018 at 10:15 GMT_

----

We also need to include the following documentation:
- A design/architecture document
- A user guide
- An SDK user guide (for all SDKs)
- An application developer guide

**Comment by dsigdosystem** [comment]
<a href="https://github.com/miguems"><img src="https://avatars3.githubusercontent.com/u/4958981?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [miguems](https://github.com/miguems)**
_Saturday Sep 15, 2018 at 17:48 GMT_

----

Have there been any discussions on creating a user manual for each app/package? Maybe a good idea to also have a template for those.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Monday Sep 17, 2018 at 01:39 GMT_

----

@miguems, we did not discuss on apps as yet. Fully agree that those need to be documented as well.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/davidbirchwork"><img src="https://avatars3.githubusercontent.com/u/11289564?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davidbirchwork](https://github.com/davidbirchwork)**
_Tuesday Sep 18, 2018 at 10:30 GMT_

----

Suggest we use API documentation compatible with https://swagger.io/ 
For .net API's https://github.com/domaindrivendev/Swashbuckle.AspNetCore will generate compatible doc and HTML viewers directly from code doc.

**Comment by dsigdosystem** [comment]
<a href="https://github.com/senakafdo"><img src="https://avatars3.githubusercontent.com/u/3415383?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [senakafdo](https://github.com/senakafdo)**
_Thursday Sep 20, 2018 at 21:01 GMT_

----

All OVE core and OVE apps APIs are now documented using Swagger. To find an interactive listing of the APIs visit, `http://{URL}/api-docs/` (works for OVE core and each app).

**Comment by senakafdo** [comment]
@jamesscottbrown, can you please fix the following in the SVG images used in INTRODUCTION.md:
1. The sections on `managing sections` and `managing state` have images with non-equal physical dimensions and font-sizes making it look unprofessional.
2. The font sizes of other images on this page are also not consistent.
3. The `images/tiling.svg` has some text that are drawn insteaf of typed. Also the spacing of text have changed when `ove.layout` changed to `ove.geometry`.
4. Only the top and left margins are set. The right and bottom margins are never set.
5. What you have defined as `x` and `y` needs to be fixed to `width` and `height`. The `images/tiling.svg` as-is is misleading.

**Comment by senakafdo** [comment]
What's pending are:
1. A design/architecture document/section explaining key components of OVE.
2. Updates to SVG images on https://ove.readthedocs.io/en/latest/docs/BASIC_CONCEPTS.html.
3. Tutorials on using OVE in real-world projects.

**Comment by senakafdo** [comment]
@jamesscottbrown will be updating the SVG images on https://ove.readthedocs.io/en/latest/docs/BASIC_CONCEPTS.html for the 0.4 release (the second point of the comment above).

Also, #19 will be addressing the third point of the comment above.

**Comment by senakafdo** [comment]
The remaining points on this issue are now addressed in #19 and #31. Therefore, I am closing this issue.
