### ISSUE TITLE
[Documentation Versioning] latest version of docs does not match installer

### ISSUE THREAD

**Issue by susanmulcahy** [ove/ove-docs#15]
this can be solved by versioning the documentation

**Comment by senakafdo** [comment]
The issues with the current installer has been fixed in ove/ove-install@af533d6. However, we still need to version the docs and then update the installer to respect such a versioning format, which we do not have as yet.

**Comment by oserban** [comment]
The issue is with the documentation version. I personally think this is a terrible practice to advise people to install latest-unstable as their default version. Reverted the install scripts to a stable version and we'll need to figure out documentation versioning.
