### ISSUE TITLE
Describe recommended Chrome configuration

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-docs#21]
@senakafdo pointed out that we should describe the recommended configuration of Chrome, which includes running it in Incongito mode and changing some default policies (audo/video autoplaying? heap size?).

**Comment by senakafdo** [comment]
The issue ove/ove-apps#131, can also be solved by resolving this issue. We need to explain things like changing the autoplay policy for audio/video etc in addition to configuration parameters required when launching chrome as well as the recommendation to run incognito etc.
